In [2]:
import pandas as pd


import openmeteo_requests
import requests_cache
from retry_requests import retry

In [ ]:
df_provs = pd.read_excel("_Provincias_Info.xlsx", sheet_name="df_LatLon")
df_provs["lat"] = df_provs["Lat"].astype(float)
df_provs["lon"] = df_provs["Lon"].astype(float)
df_provs["prov"] = df_provs["Nombre"].astype(str)
df_provs["code"] = df_provs["CODIGO"].astype("Int8")
df_provs.drop(columns=["Lat", "Lon", "Nombre", "CODIGO"], inplace=True)
# df_provs.to_csv("Provinces_data.csv", index=False)
df_provs

,Capital,Comunidad autónoma,Nombre oficial,Poblacion,Superficie,%Poblacion,%Superficie2,lat,lon,prov,code
0,Madrid,Comunidad de Madrid,Madrid,7113886,8028,0.144802,0.015866,40.495,-3.7170,Madrid,28
1,Barcelona,Cataluña,Barcelona,5959941,7728,0.121314,0.015273,41.730,1.9837,Barcelona,8
2,Valencia,Comunitat Valenciana,Valencia/València,2763996,10807,0.056261,0.021358,39.370,-0.8000,Valencia,46
3,Alicante,Comunitat Valenciana,Alicante/Alacant,2033566,5817,0.041393,0.011496,38.478,-0.5680,Alicante,3
4,Sevilla,Andalucía,Sevilla,1977664,14036,0.040255,0.027740,37.435,-5.6820,Sevilla,41
5,Málaga,Andalucía,Málaga,1791183,7306,0.036459,0.014439,36.813,-4.7250,Málaga,29
6,Murcia,Región de Murcia,Murcia,1586989,11314,0.032303,0.022360,38.002,-1.4850,Murcia,30
7,Cádiz,Andalucía,Cádiz,1261420,7440,0.025676,0.014704,36.553,-5.7600,Cádiz,11
8,Palma,Illes Balears,"Balears, Illes",1249844,4992,0.025440,0.009866,39.574,2.9124,Islas Baleares,7
9,Las Palmas de Gran Canaria,Canarias,"Palmas, Las",1171547,4066,0.023847,0.008036,28.365,-14.5400,Las Palmas,35
10,Bilbao,País Vasco,Bizkaia,1167233,2217,0.023759,0.004381,43.238,-2.8510,Vizcaya,48
11,La Coruña,Galicia,"Coruña, A",1135623,7950,0.023115,0.015712,43.126,-8.4640,La Coruña,15
12,Santa Cruz de Tenerife,Canarias,Santa Cruz de Tenerife,1087319,3381,0.022132,0.006682,28.312,-17.0100,Santa Cruz de Tenerife,38
13,Oviedo,Principado de Asturias,Asturias,1015128,10604,0.020663,0.020957,43.292,-5.9930,Asturias,33
14,Zaragoza,Aragón,Zaragoza,998443,17274,0.020323,0.034139,41.620,-1.0640,Zaragoza,50
15,Pontevedra,Galicia,Pontevedra,947818,4495,0.019293,0.008884,42.435,-8.4610,Pontevedra,36
16,Granada,Andalucía,Granada,945797,12647,0.019252,0.024994,37.312,-3.2670,Granada,18
17,Tarragona,Cataluña,Tarragona,875530,6303,0.017821,0.012457,41.087,0.8180,Tarragona,43
18,Gerona,Cataluña,Girona,830429,5910,0.016903,0.011680,42.127,2.6733,Gerona,17
19,Córdoba,Andalucía,Córdoba,773163,13771,0.015738,0.027216,37.992,-4.8090,Córdoba,14
20,Almería,Andalucía,Almería,770554,8775,0.015685,0.017342,37.196,-2.3440,Almería,4
21,Toledo,Castilla-La Mancha,Toledo,755081,15370,0.015370,0.030376,39.793,-4.1480,Toledo,45
22,San Sebastián,País Vasco,Gipuzkoa,733149,1980,0.014923,0.003913,43.143,-2.1940,Guipúzcoa,20
23,Pamplona,Comunidad Foral de Navarra,Navarra,683854,10391,0.013920,0.020536,42.667,-1.6460,Navarra,31
24,Badajoz,Extremadura,Badajoz,665155,21766,0.013539,0.043016,38.709,-6.1410,Badajoz,6
25,Castellón de la Plana,Comunitat Valenciana,Castellón/Castelló,627620,6636,0.012775,0.013115,40.241,-0.1460,Castellón,12
26,Jaén,Andalucía,Jaén,618143,13496,0.012582,0.026672,38.016,-3.4410,Jaén,23
27,Santander,Cantabria,Cantabria,593623,5321,0.012083,0.010516,43.197,-4.0290,Cantabria,39
28,Huelva,Andalucía,Huelva,538789,10128,0.010967,0.020016,37.577,-6.8290,Huelva,21
29,Valladolid,Castilla y León,Valladolid,528644,8110,0.010760,0.016028,41.634,-4.8470,Valladolid,47
30,Ciudad Real,Castilla-La Mancha,Ciudad Real,494848,19813,0.010073,0.039157,38.925,-3.8280,Ciudad Real,13
31,Lérida,Cataluña,Lleida,458226,12172,0.009327,0.024056,42.043,1.0476,Lérida,25
32,León,Castilla y León,León,448030,15581,0.009120,0.030793,42.619,-5.8390,León,24
33,Albacete,Castilla-La Mancha,Albacete,390751,14924,0.007954,0.029495,38.825,-1.9800,Albacete,2
34,Cáceres,Extremadura,Cáceres,388190,19868,0.007902,0.039265,39.711,-6.1600,Cáceres,10
35,Burgos,Castilla y León,Burgos,362663,14292,0.007382,0.028246,42.368,-3.5850,Burgos,9
36,Vitoria,País Vasco,Araba/Álava,341961,3037,0.006961,0.006002,42.835,-2.7200,Álava,1
37,Salamanca,Castilla y León,Salamanca,328446,12350,0.006685,0.024408,40.804,-6.0650,Salamanca,37
38,Logroño,La Rioja,"Rioja, La",326803,5045,0.006652,0.009971,42.274,-2.5170,La Rioja,26
39,Lugo,Galicia,Lugo,326022,9856,0.006636,0.019479,43.011,-7.4460,Lugo,27
40,Orense,Galicia,Ourense,305278,7273,0.006214,0.014374,42.196,-7.5920,Orense,32
41,Guadalajara,Castilla-La Mancha,Guadalajara,285839,12214,0.005818,0.024139,40.813,-2.6230,Guadalajara,19
42,Huesca,Aragón,Huesca,230087,15636,0.004683,0.030902,42.203,-0.0720,Huesca,22
43,Cuenca,Castilla-La Mancha,Cuenca,199859,17140,0.004068,0.033874,39.896,-2.1950,Cuenca,16
44,Zamora,Castilla y León,Zamora,165564,10561,0.003370,0.020872,41.727,-5.9800,Zamora,49
45,Ávila,Castilla y León,Ávila,160738,8050,0.003272,0.015909,40.571,-4.9450,Ávila,5
46,Palencia,Castilla y León,Palencia,158702,8052,0.003230,0.015913,42.371,-4.5350,Palencia,34
47,Segovia,Castilla y León,Segovia,158251,6921,0.003221,0.013678,41.170,-4.0540,Segovia,40
48,Teruel,Aragón,Teruel,136091,14810,0.002770,0.029269,40.661,-0.8150,Teruel,44
49,Soria,Castilla y León,Soria,90183,10306,0.001836,0.020368,41.620,-2.5880,Soria,42
50,-,Ciudad Autónoma de Melilla,Melilla,87067,13,0.001772,0.000026,35.291,-2.9500,Melilla,52
51,-,Ciudad Autónoma de Ceuta,Ceuta,83567,19,0.001701,0.000038,35.893,-5.3420,Ceuta,51

In [4]:
num_init = 0
num_end = 10


# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = -1)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://archive-api.open-meteo.com/v1/archive"
city_names = df_provs.iloc[num_init:num_end+1]["prov"].to_list()
params = {
	"latitude":df_provs.iloc[num_init:num_end+1]["lat"].to_list(),
	"longitude":df_provs.iloc[num_init:num_end+1]["lon"].to_list(),
	"start_date": "2020-01-01",
	"end_date": "2026-03-24",
	"daily": ["weather_code", "temperature_2m_mean", "temperature_2m_max", "temperature_2m_min", "apparent_temperature_mean", "wind_speed_10m_max", "wind_gusts_10m_max", "shortwave_radiation_sum", "sunrise", "sunset", "daylight_duration", "precipitation_sum", "rain_sum", "snowfall_sum", "precipitation_hours", "surface_pressure_mean", "et0_fao_evapotranspiration_sum"],
}
responses = openmeteo.weather_api(url, params = params)

city_frames = []

# Process all locations and collect a dataframe per city
for city_name, response in zip(city_names, responses):
	print(f"\nCity: {city_name}")
	print(f"Coordinates: {response.Latitude()}°N {response.Longitude()}°E")
	print(f"Elevation: {response.Elevation()} m asl")
	print(f"Timezone difference to GMT+0: {response.UtcOffsetSeconds()}s")
	
	# Process daily data. The order of variables needs to be the same as requested.
	daily = response.Daily()
	daily_weather_code = daily.Variables(0).ValuesAsNumpy()
	daily_temperature_2m_mean = daily.Variables(1).ValuesAsNumpy()
	daily_temperature_2m_max = daily.Variables(2).ValuesAsNumpy()
	daily_temperature_2m_min = daily.Variables(3).ValuesAsNumpy()
	daily_apparent_temperature_mean = daily.Variables(4).ValuesAsNumpy()
	daily_wind_speed_10m_max = daily.Variables(5).ValuesAsNumpy()
	daily_wind_gusts_10m_max = daily.Variables(6).ValuesAsNumpy()
	daily_shortwave_radiation_sum = daily.Variables(7).ValuesAsNumpy()
	daily_sunrise = daily.Variables(8).ValuesInt64AsNumpy()
	daily_sunset = daily.Variables(9).ValuesInt64AsNumpy()
	daily_daylight_duration = daily.Variables(10).ValuesAsNumpy()
	daily_precipitation_sum = daily.Variables(11).ValuesAsNumpy()
	daily_rain_sum = daily.Variables(12).ValuesAsNumpy()
	daily_snowfall_sum = daily.Variables(13).ValuesAsNumpy()
	daily_precipitation_hours = daily.Variables(14).ValuesAsNumpy()
	daily_surface_pressure_mean = daily.Variables(15).ValuesAsNumpy()
	daily_et0_fao_evapotranspiration_sum = daily.Variables(16).ValuesAsNumpy()
	
	daily_data = {"date": pd.date_range(
		start = pd.to_datetime(daily.Time(), unit = "s", utc = True),
		end =  pd.to_datetime(daily.TimeEnd(), unit = "s", utc = True),
		freq = pd.Timedelta(seconds = daily.Interval()),
		inclusive = "left"
	)}
	
	daily_data["weather_code"] = daily_weather_code
	daily_data["temperature_2m_mean"] = daily_temperature_2m_mean
	daily_data["temperature_2m_max"] = daily_temperature_2m_max
	daily_data["temperature_2m_min"] = daily_temperature_2m_min
	daily_data["apparent_temperature_mean"] = daily_apparent_temperature_mean
	daily_data["wind_speed_10m_max"] = daily_wind_speed_10m_max
	daily_data["wind_gusts_10m_max"] = daily_wind_gusts_10m_max
	daily_data["shortwave_radiation_sum"] = daily_shortwave_radiation_sum
	daily_data["sunrise"] = daily_sunrise
	daily_data["sunset"] = daily_sunset
	daily_data["daylight_duration"] = daily_daylight_duration
	daily_data["precipitation_sum"] = daily_precipitation_sum
	daily_data["rain_sum"] = daily_rain_sum
	daily_data["snowfall_sum"] = daily_snowfall_sum
	daily_data["precipitation_hours"] = daily_precipitation_hours
	daily_data["surface_pressure_mean"] = daily_surface_pressure_mean
	daily_data["et0_fao_evapotranspiration_sum"] = daily_et0_fao_evapotranspiration_sum
	
	daily_city_df = pd.DataFrame(data = daily_data)
	daily_city_df["city"] = city_name
	city_frames.append(daily_city_df)

daily_dataframe_2 = pd.concat(city_frames, ignore_index = True)
daily_dataframe_2

City: Madrid
Coordinates: 40.52724075317383°N -3.686431884765625°E
Elevation: 660.0 m asl
Timezone difference to GMT+0: 0s

City: Barcelona
Coordinates: 41.72231674194336°N 1.9536901712417603°E
Elevation: 567.0 m asl
Timezone difference to GMT+0: 0s

City: Valencia
Coordinates: 39.40245819091797°N -0.745849609375°E
Elevation: 346.0 m asl
Timezone difference to GMT+0: 0s

City: Alicante
Coordinates: 38.48857498168945°N -0.610565185546875°E
Elevation: 508.0 m asl
Timezone difference to GMT+0: 0s

City: Sevilla
Coordinates: 37.4340934753418°N -5.625°E
Elevation: 185.0 m asl
Timezone difference to GMT+0: 0s

City: Málaga
Coordinates: 36.8014030456543°N -4.730621337890625°E
Elevation: 370.0 m asl
Timezone difference to GMT+0: 0s

City: Murcia
Coordinates: 37.996482849121094°N -1.451629638671875°E
Elevation: 526.0 m asl
Timezone difference to GMT+0: 0s

City: Cádiz
Coordinates: 36.52021026611328°N -5.76470947265625°E
Elevation: 309.0 m asl
Timezone difference to GMT+0: 0s

City: Islas Baleares
Coordinates: 39.54305648803711°N 2.8670361042022705°E
Elevation: 173.0 m asl
Timezone difference to GMT+0: 0s

City: Las Palmas
Coordinates: 28.36555290222168°N -14.506256103515625°E
Elevation: 0.0 m asl
Timezone difference to GMT+0: 0s

City: Vizcaya
Coordinates: 43.268890380859375°N -2.82513427734375°E
Elevation: 79.0 m asl
Timezone difference to GMT+0: 0s

,date,weather_code,temperature_2m_mean,temperature_2m_max,temperature_2m_min,apparent_temperature_mean,wind_speed_10m_max,wind_gusts_10m_max,shortwave_radiation_sum,sunrise,sunset,daylight_duration,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,surface_pressure_mean,et0_fao_evapotranspiration_sum,city
0,2020-01-01 00:00:00+00:00,2.0,3.147917,11.25,-2.30,0.386449,9.178235,11.520000,9.330000,1577864282,1577897875,33592.332031,0.0,0.0,0.0,0.0,952.290039,1.082871,Madrid
1,2020-01-02 00:00:00+00:00,3.0,2.483333,9.30,-2.50,-0.423794,8.534353,12.959999,9.230000,1577950689,1577984326,33636.273438,0.0,0.0,0.0,0.0,951.688293,1.020405,Madrid
2,2020-01-03 00:00:00+00:00,3.0,1.568750,6.60,-1.50,-1.070321,8.209263,12.959999,6.720000,1578037094,1578070778,33683.929688,0.0,0.0,0.0,0.0,953.317322,0.700336,Madrid
3,2020-01-04 00:00:00+00:00,1.0,3.754167,10.25,-1.25,0.239713,17.057314,38.160000,8.870000,1578123497,1578157232,33735.214844,0.0,0.0,0.0,0.0,954.555420,1.079652,Madrid
4,2020-01-05 00:00:00+00:00,0.0,3.179167,11.45,-2.35,0.025346,9.931042,19.440001,9.410000,1578209897,1578243688,33790.031250,0.0,0.0,0.0,0.0,950.722839,1.111593,Madrid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25020,2026-03-20 00:00:00+00:00,3.0,12.800000,19.50,7.05,10.342389,14.003029,32.760002,19.309999,1773987254,1774030989,43733.839844,0.0,0.0,0.0,0.0,1002.611389,3.358055,Vizcaya
25021,2026-03-21 00:00:00+00:00,3.0,10.904166,17.90,5.00,8.982385,10.993271,27.719999,19.680000,1774073548,1774117460,43911.101562,0.0,0.0,0.0,0.0,1002.135193,3.047693,Vizcaya
25022,2026-03-22 00:00:00+00:00,51.0,9.250001,15.25,3.10,7.451178,17.782686,41.399998,18.990000,1774159843,1774203932,44087.492188,0.4,0.4,0.0,4.0,1004.717285,2.488391,Vizcaya
25023,2026-03-23 00:00:00+00:00,51.0,9.522917,14.35,4.85,7.798176,11.341428,28.440001,16.090000,1774246138,1774290403,44263.125000,0.9,0.9,0.0,5.0,1010.509277,2.198060,Vizcaya
25024,2026-03-24 00:00:00+00:00,3.0,9.750001,17.90,2.25,8.314380,9.195868,23.400000,20.170000,1774332433,1774376874,44439.250000,0.0,0.0,0.0,0.0,1012.891663,2.965956,Vizcaya

In [5]:
extract_date = pd.to_datetime("today")
place = "top0-10_cities"
dates_from_to = "2020-2026"
csv_title = f"daily_{place}_{dates_from_to}_{extract_date.strftime('%Y-%m-%d')}_extracted.csv"

daily_dataframe_2.to_csv(csv_title, index = False)
daily_dataframe_2

,date,weather_code,temperature_2m_mean,temperature_2m_max,temperature_2m_min,apparent_temperature_mean,wind_speed_10m_max,wind_gusts_10m_max,shortwave_radiation_sum,sunrise,sunset,daylight_duration,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,surface_pressure_mean,et0_fao_evapotranspiration_sum,city
0,2020-01-01 00:00:00+00:00,2.0,3.147917,11.25,-2.30,0.386449,9.178235,11.520000,9.330000,1577864282,1577897875,33592.332031,0.0,0.0,0.0,0.0,952.290039,1.082871,Madrid
1,2020-01-02 00:00:00+00:00,3.0,2.483333,9.30,-2.50,-0.423794,8.534353,12.959999,9.230000,1577950689,1577984326,33636.273438,0.0,0.0,0.0,0.0,951.688293,1.020405,Madrid
2,2020-01-03 00:00:00+00:00,3.0,1.568750,6.60,-1.50,-1.070321,8.209263,12.959999,6.720000,1578037094,1578070778,33683.929688,0.0,0.0,0.0,0.0,953.317322,0.700336,Madrid
3,2020-01-04 00:00:00+00:00,1.0,3.754167,10.25,-1.25,0.239713,17.057314,38.160000,8.870000,1578123497,1578157232,33735.214844,0.0,0.0,0.0,0.0,954.555420,1.079652,Madrid
4,2020-01-05 00:00:00+00:00,0.0,3.179167,11.45,-2.35,0.025346,9.931042,19.440001,9.410000,1578209897,1578243688,33790.031250,0.0,0.0,0.0,0.0,950.722839,1.111593,Madrid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25020,2026-03-20 00:00:00+00:00,3.0,12.800000,19.50,7.05,10.342389,14.003029,32.760002,19.309999,1773987254,1774030989,43733.839844,0.0,0.0,0.0,0.0,1002.611389,3.358055,Vizcaya
25021,2026-03-21 00:00:00+00:00,3.0,10.904166,17.90,5.00,8.982385,10.993271,27.719999,19.680000,1774073548,1774117460,43911.101562,0.0,0.0,0.0,0.0,1002.135193,3.047693,Vizcaya
25022,2026-03-22 00:00:00+00:00,51.0,9.250001,15.25,3.10,7.451178,17.782686,41.399998,18.990000,1774159843,1774203932,44087.492188,0.4,0.4,0.0,4.0,1004.717285,2.488391,Vizcaya
25023,2026-03-23 00:00:00+00:00,51.0,9.522917,14.35,4.85,7.798176,11.341428,28.440001,16.090000,1774246138,1774290403,44263.125000,0.9,0.9,0.0,5.0,1010.509277,2.198060,Vizcaya
25024,2026-03-24 00:00:00+00:00,3.0,9.750001,17.90,2.25,8.314380,9.195868,23.400000,20.170000,1774332433,1774376874,44439.250000,0.0,0.0,0.0,0.0,1012.891663,2.965956,Vizcaya