In [30]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
# pd.reset_option('display.max_colwidth')

1. Introduction

2. Gata Gathering

    2.1 Weather Data

To gather data regarding weather we took it from several places.
We used https://open-meteo.com/en/docs api to get the weather data for all the 51 provinces in Spain (we took the capital of each province as the location for the weather data).
We got information from precipitation, sunny hours, Cloud Cover, windspeed, humidity and temperature. We used the data from the years 2020 to 2026 (until march 2026).

Doing that, we were creating a Dataframe of 115,566 rows (2,266 days from 01/01/2020 to 24/03/2026 x 51 provinces in Spain) and 18 columns, named as following:

In [28]:
df1 = pd.read_excel("Info_Columns.xlsx", sheet_name="Weather_Info")
display(df1)

,Variable,Unit,Description
0,date,YYYY-MM-DD,The calendar date of the weather data.
1,weather_code,WMO code (0-99),"The most severe weather condition on a given day, represented by a WMO (World Meteorological Organization) numeric code (0-99)."
2,temperature_2m_mean,°C,Mean daily air temperature at 2 meters above ground. (in
3,temperature_2m_max,°C,Maximum daily air temperature at 2 meters above ground.
4,temperature_2m_min,°C,Minimum daily air temperature at 2 meters above ground.
5,apparent_temperature_mean,°C,"Mean daily apparent temperature. This is the ""feels-like"" temperature, taking wind chill and humidity into account."
6,wind_speed_10m_max,km/h,Maximum wind speed over the day at 10 meters above ground level.
7,wind_gusts_10m_max,km/h,Maximum wind gust speed over the day at 10 meters above ground level.
8,shortwave_radiation_sum,MJ/m²,Total daily sum of shortwave solar radiation reaching the surface (typically in MJ/m²).
9,sunrise,YYYY-MM-DDTHH:MM,Time of sunrise.
10,sunset,YYYY-MM-DDTHH:MM,Time of sunset.
11,daylight_duration,seconds (s),Total duration of daylight for the day (typically measured in seconds).
12,precipitation_sum,mm,"Total daily sum of all precipitation (including rain, showers, and snow water equivalent)."
13,rain_sum,mm,Total daily sum of rain only.
14,snowfall_sum,cm,Total daily sum of snowfall.
15,precipitation_hours,hours (h),The total number of hours with precipitation recorded on a given day.
16,surface_pressure_mean,hPa,Mean daily atmospheric air pressure at surface elevation.
17,et0_fao_evapotranspiration_sum,mm,"Daily sum of ET₀ Reference Evapotranspiration, representing the evaporation from a well-watered grass field."

    2.2 Population and Area Data

Like there is a unique price for the whole country, we need to have 1 value (of price) every single day. To do that, we have weighted every province by 2 different fields: Population and area.

To get info regarding population and area we have used the data from https://www.ine.es/, the Spanish National Statitics Institute

In [29]:
df_2 = pd.read_excel("Info_Columns.xlsx", sheet_name="Cities_Info")
display(df_2)

,Variable,Description
0,Province Name,"Name of the Spanish Province, equivalent to the most important city. (There are 52 in total)"
1,Autonomous Comunity,Name of the Autonomous Community (there are 17 in total)
2,Code,Code between 1 and 52
3,Population,Number of inhabitants of the province
4,Surface,km^2 of the province
5,%Population,Compared to the whole country
6,%Surface,Compared to the whole country
7,Latitude (of the Capital City),Geographical WGS84 coordinates of the capital city.
8,Longitude (of the Capital City),Geographical WGS84 coordinates of the capital city.

    2.3 Final table

Once we have this information, the aggregated table has been done. We have decided not to include every province in the final dataframe, as we consider there are higly correlated.
So, to get every column of the final table, this considerations have been made:
- **Weighting average by Population**: Columns weather_code, temperature_2m_mean, temperature_2m_max, temperature_2m_min, apparent_temperature_mean*
- **Weighting average by Surface**: Columns *wind_speed_10m_max, wind_gusts_10m_max, shortwave_radiation_sum, precipitation_sum, rain_sum, snowfall_sum, precipitation_hours, surface_pressure_mean, et0_fao_evapotranspiration_sum*
- **Take Madrid (most important city and in the middle of the country)**: Columns *sunrise, sunset*
- **Not taken columns**: *daylight_duration* As it has a high correlation with sunrise and sunset columns

<br />

Also, some derived weather features have been added:
- **daily_temperature_range**: Maximum daily temperature - Minimum Daily temperature
- **rolling_avg_temp**: AVG temperature of last 3 days (not counting current).
- **delta_temp_with previous**: abs(Avg daily temp - rolling_avg_temp)

- **peninsular_max_temperature**: Maximum of all temperatures (excludind Canary Islands, Balearic Islands, Ceuta and Melilla).
- **peninsular_min_temperature**: Minimum of all temperatures (excludind Canary Islands, Balearic Islands, Ceuta and Melilla)
- **max_windspeed**: As the eolic energy does not grow linearly (in a cubic way), the maximum speed can contribute quite a lot 

**When taking maximums and minimums, the 3th biggest number has been taken (not the first and second to mitigate outliers)**

<br />

Also, following columns have been added in order to give more valuable information
- **Day_of_the_week**: (1 for Monday, 7 for Sunday)
- **Is_weekend**: (Binary variable)
- **Is_natinal_holiday**: (Binary variable)

3. Conclusion